default_branch: main
delete_branch_on_merge: true
enable_automated_security_fixes: true
enable_vulnerability_alerts: true
milestones:
  - title: alpha
    description: first internal release
    state: open
  - title: beta
    description: last internal release
    state: open
  - title: POC
    description: Proof Of Concept
    state: open
  - title: MVP
    description: Minimal Valuable Product
    state: open
  - title: v1.0.0
    description: 1st production-ready release
    state: open
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      enforce_admins: true
      required_linear_history: true
  - name: dev
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      enforce_admins: true
      required_linear_history: true
  - name: ops
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      enforce_admins: true
      required_linear_history: true
labels:
  # type of issue
  - name: "bug"
    color: "#B60205"
    description: "Related to non-working things or strange behaviors"
  - name: "feat"
    color: "#0E8A16"
    description: "Related to new features and implementations"
  - name: "explo"
    color: "#FBCA04"
    description: "Related to new things I don't know how to do"

  # languages
  - name: "bash"
    color: "#300A24"
    description: "Related to Bash files modifications"
  - name: "golang"
    color: "#00A9DA"
    description: "Related to Golang files modifications"
  - name: "js"
    color: "#F0EE00"
    description: "Related to Vuejs / JavaScript files modifications"
  - name: "docker"
    color: "#2497ED"
    description: "Related to Dockerfiles and Docker Compose files modifications"
  - name: "kubernetes"
    color: "#326CE5"
    description: "Related to Terraform files modifications"
  - name: "terraform"
    color: "#7B42BC"
    description: "Related to Terraform files modifications"

  # scope
  - name: "dev" 
    color: "#5319E7"
    description: "Related to CI/CD files modifications"
  - name: "ops" 
    color: "#D93F0B"
    description: "Related to CI/CD files modifications"
  - name: "cicd" 
    color: "#006B75"
    description: "Related to CI/CD files modifications"
  - name: "doc"
    color: "#0052CC"
    description: "Related to documentation, project illustrations"
  
  # us
  - name: "[US] developer"
    color: "#C2E0C6"
    description: "As a developer, I want to [...]"
  - name: "[US] user"
    color: "#C5DEF5"
    description: "As a user, I want to [...]"
  - name: "[US] ops/repo manager"
    color: "#D4C5F9"
    description: "As a repowner, I want to [...]"

