name: " WEB [CI]"

on:
  push:
    paths:
      - '**/*.js'
      - '**/*.json'
      - '**/*.vue'
      - "web/"


jobs:
  BUILD:
    name: BUILD
    runs-on: ubuntu-latest
    env:
      wd: web/
    steps:
      # Checkout to current workspace
    - name: 1 - CHECKOUT
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

      # Install Golang with specific version
    - name: 2 - SETUP NODE@16
      uses: actions/setup-node@v3
      with:
        node-version: 16

      # Cache Go modules to make the build faster

    - name: 3 - GET NPM CACHE DIRECTORY
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - name: 4 - CACHE NODE MODULES
      uses: actions/cache@v3
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Install packages
    - name: 5 - NPM INSTALL
      run: npm install
      working-directory: ${{ env.wd }}

    # Build apps
    - name: 4 - BUILD
      run: npm run build
      working-directory: ${{ env.wd }}